# Generated by Django 4.1.3 on 2022-12-08 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_type', models.CharField(choices=[('spr', 'Spring'), ('fal', 'fall'), ('win', 'winterim'), ('sum', 'summer')], default='fal', max_length=3)),
                ('term_year', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2022', max_length=4)),
                ('course_number', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('assigned_people', models.ManyToManyField(to='TA_Scheduler.account')),
            ],
        ),
        migrations.CreateModel(
            name='UsAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', localflavor.us.models.USStateField(default='WI', max_length=2)),
                ('city', models.CharField(default='Milwaukee', max_length=128)),
                ('street_address', models.CharField(max_length=128)),
                ('zip_code', localflavor.us.models.USZipCodeField(default='53201', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=6)),
                ('section', models.CharField(max_length=4)),
                ('type', models.CharField(choices=[('LEC', 'Lecture'), ('DIS', 'Discussion'), ('LAB', 'Lab')], default='LAB', max_length=3)),
                ('meet_monday', models.BooleanField(default=False)),
                ('meet_tuesday', models.BooleanField(default=False)),
                ('meet_wednesday', models.BooleanField(default=False)),
                ('meet_thursday', models.BooleanField(default=False)),
                ('meet_friday', models.BooleanField(default=False)),
                ('meet_start', models.TimeField(null=True)),
                ('meet_end', models.TimeField(null=True)),
                ('assigned_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TA_Scheduler.account')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.course')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.usaddress'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
