# Generated by Django 4.1.3 on 2022-11-30 23:41

from django.db import migrations

from TA_Scheduler.groups import init_groups


class Migration(migrations.Migration):
    dependencies = [
        ('TA_Scheduler', '0001_initial'),
    ]

    operations = [

        migrations.RunPython(init_groups)

    ]
