# Generated by Django 4.1.4 on 2022-12-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0002_make_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserestrictions',
            name='current_sections',
        ),
    ]
