# Generated by Django 4.1.4 on 2022-12-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0002_make_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assigned_people',
            field=models.ManyToManyField(blank=True, to='TA_Scheduler.account'),
        ),
    ]
