# Generated by Django 4.1.4 on 2022-12-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0003_alter_course_assigned_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TA_Scheduler.account'),
        ),
    ]
